[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
DimensionalData = "0703355e-b756-11e9-17c0-8b28908087d0"
DiskArrays = "3c3547ce-8d99-4f5e-a174-61eb10b00ae3"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
GeoMakie = "db073c08-6b98-4ee5-b6a4-5efafb3259c6"
HiddenMarkovModels = "84ca31d5-effc-45e0-bfda-5a68cd981f47"
LaTeXStrings = "b964fa9f-0449-5b57-a5c2-d3ea65f4040f"
MultivariateStats = "6f286f6a-111f-5878-ab1e-185364afe411"
NCDatasets = "85f8d34a-cbdd-5861-8df4-14fed0d494ab"
NaturalEarth = "436b0209-26ab-4e65-94a9-6526d86fea76"
NetCDF = "30363a11-5582-574a-97bb-aa9a979735b9"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
TidierData = "fe2206b3-d496-4ee9-a338-6a095c4ece80"
TidierFiles = "8ae5e7a9-bdd3-4c93-9cc3-9df4d5d947db"
YAXArrays = "c21b50f5-aa40-41ea-b809-c0f5e47bfa5c"
